apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  region: <us-west-2>
  version: '<1.18>'
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: daydin41/udacity-cloud-devops-capstone:new
        imagePullPolicy: Always
        name: capstone-project-cloud-devops
        ports:
          - containerPort: 80

